spring:
  application:
    name: backend
    frontend-url: ${FRONTEND_URL:http://localhost:5173}
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      # Close auto DDL Generation
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

jwt:
  access-secret: ${JWT_ACCESS_SECRET:Yn2kj3h4g5f6d7s8a9w0e1r2t3y4u5i6o7p8q9z0x1c2v3b4n5m6}
  refresh-secret: ${JWT_REFRESH_SECRET:Lp9o8i7u6y5t4r3e2w1q0a9z8x7c6v5b4n3m2k1j0h9g8f7d6s5a4}